CREATE TABLE `ta_tnetvalueday_load` (
  `l_rowid` INT(11) NOT NULL AUTO_INCREMENT,
  `c_tenantid` VARCHAR(20) NOT NULL DEFAULT ' ',
  `c_tacode` VARCHAR(2) NOT NULL DEFAULT ' ',
  `d_netvaluedate` INT(11) NOT NULL DEFAULT '0',
  `d_cdate` INT(11) NOT NULL DEFAULT '0',
  `c_fundcode` VARCHAR(12) NOT NULL DEFAULT ' ',
  `f_netvalue` DECIMAL(7,4) NOT NULL DEFAULT '1.0000',
  `f_lasttotalshare` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_lasttotalasset` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_asucceed` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_rsucceed` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `c_vastflag` VARCHAR(1) NOT NULL DEFAULT ' ',
  `f_encashratio` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000',
  `f_changeratio` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000',
  `c_excessflag` VARCHAR(1) NOT NULL DEFAULT ' ',
  `f_subscriberatio` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000',
  `c_inputpersonnel` VARCHAR(16) NOT NULL DEFAULT ' ',
  `c_checkpersonnel` VARCHAR(16) NOT NULL DEFAULT ' ',
  `f_fundtotalincome` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_incomeunit` DECIMAL(10,5) NOT NULL DEFAULT '0.00000',
  `f_totalnetvalue` DECIMAL(7,4) NOT NULL DEFAULT '0.0000',
  `f_incomeratio` DECIMAL(9,6) NOT NULL DEFAULT '0.000000',
  `f_servicefare` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_assign` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_unassign` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_growthrate` DECIMAL(9,8) NOT NULL DEFAULT '0.00000000',
  `f_managefare` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_protectbalance` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `d_exportdate` INT(11) NOT NULL DEFAULT '0',
  `c_managercode` VARCHAR(10) NOT NULL DEFAULT ' ',
  `c_flowcode` VARCHAR(3) NOT NULL DEFAULT ' ',
  `f_lastunassign` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_structuredratio` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000',
  `c_liqbatchno` VARCHAR(1) NOT NULL DEFAULT '1',
  `d_filedate` INT(11) NOT NULL DEFAULT '0',
  `f_filetotalshare` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `f_structuredtotalasset` DECIMAL(16,2) DEFAULT '0.00',
  `c_flowstep` VARCHAR(60) NOT NULL DEFAULT ' ',
  `c_loadpoint` VARCHAR(100) NOT NULL DEFAULT ' ',
  `c_datastyle` VARCHAR(30) NOT NULL DEFAULT ' ',
  PRIMARY KEY (`l_rowid`),
  UNIQUE KEY `idx_tnetvalueday` (`c_flowstep`,`c_loadpoint`,`c_datastyle`,`c_fundcode`,`d_cdate`,`c_tenantid`),
  KEY `uidx_tnetvalueday` (`c_fundcode`,`d_netvaluedate`,`c_tenantid`),
  KEY `idx_tnetvalueday_dcate` (`d_cdate`)
) ENGINE=INNODB AUTO_INCREMENT=167 DEFAULT CHARSET=gbk;